### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-css-stealing-styles-xedvDK#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-css-stealing-styles-xedvDK/) and meets the following criteria:

- [x] The page includes the name of your search engine in big letters (you can make it up), with a search `input` below it, then a button below that to run the search (the button doesn't have to do anything for this prototype)
- [x] The font size of the search engine name is at least 70 pixels, so that it's very easy to see
- [x] `span` elements are wrapped around each letter of the name, like this: `<span>G</span><span>o</span><span>o</span><span>g</span><span>l</span><span>e</span>`, so that they can be styled individually with classes
- [x] The on-hover colors from the paragraphs [on this page](http://skillful-clouds.surge.sh/) are used to color individual letters of your name (similar to the letters in Google's logo)
- [x] Inspect the `input` element at the bottom of the [_Prototyping states_ page of the lesson](5) to create an identical-looking search box for your own site (it should even use the same styles on `focus`)
- [x] The styles from the "Create Account" button [on this page](http://plant-servant.surge.sh/) are used for your "Search" button (it should even use the same styles on `hover` and `active`)
- [x] There are no stylelint errors in your CSS (this will also be expected for all future projects)
- [x] All your CSS exists in a `.css` file

Linted css using [npm stylelint](https://stylelint.io/) with the [standard config](https://github.com/stylelint/stylelint-config-standard/blob/master/index.js)
The search bar works!
EDIT: Most of the CSS is in the style.css file.. I couldn't get all the effects without some javascript though!

**Comment by stuartpearman** [comment]
@lordcrekit this is sweet!!!! Nice work, I like that you added a "Gamble" option. The letters are awesome too. There are still some CSS things you need to adjust though:

- [Check the button again](http://plant-servant.surge.sh/), there's no border on it, that looks to be the main difference between yours and the original
- Make sure the `:focus` state of the `input` element is also the same as the example (should be green without the blue glow)

Let me know if you have any questions

**Comment by lordcrekit** [comment]
Hey! The green border on the buttons was just to make it consistent with the searchbar, but I removed it.
The border was because it's an input element and not a link! I had to override it, but it should be good now. I also noticed the color was slightly off, that's fixed.

I don't understand what you meant by the second point. The only thing that had both blue and green was my buttons, and it was the green that was wrong.

**Comment by stuartpearman** [comment]
Hey William, try clicking into the input on the [Prototyping states](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/css-stealing-styles/5) page of the lesson. You'll notice the input border turns green. That same slide talks about how to use the element inspector to steal those styles.

If you get stumped, let me know and I can help you out in class.

**Comment by lordcrekit** [comment]
I see what you mean now. I had it green but it wasn't doing it in the same way as that example.
It should be good now!

**Comment by stuartpearman** [comment]
Ah, it's definitely green now! Nice work :shipit: :star: :tada:
